version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always

    env_file:
      - ".env"

